name: MX4300 NSS Build

on: workflow_dispatch

jobs:
    build:
        name: MX4300 NSS Build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt install -y build-essential \
                  clang \
                  flex \
                  bison \
                  g++ \
                  gawk \
                  gcc-multilib \
                  g++-multilib \
                  gettext \
                  git \
                  libncurses5-dev \
                  libssl-dev \
                  python3-setuptools \
                  rsync \
                  swig \
                  unzip \
                  zlib1g-dev \
                  file \
                  wget && \
                  sudo apt-get clean

            - name: Reclaim space for large builds
              run: rm -rf /opt/hostedtoolcache

            - name: Checkout
              uses: actions/checkout@v4

            - name: Clone config
              run: git clone https://${{ secrets.PAT }}@github.com/fhirrepo/custom_openwrt.git files/etc/uci-defaults && rm -rf files/etc/uci-defaults/.git && rm -rf files/etc/uci-defaults/*.yml

            - name: Update feeds
              # run:  make package/symlinks
              run: cp feeds.conf.default feeds.conf
               && scripts/feeds update -a
               && scripts/feeds install -a

            - name: Generate MX4300 NSS Config
              run: cp nss-setup/config-nss.seed .config
               && sed -i 's/# CONFIG_TARGET_qualcommax_ipq807x_DEVICE_linksys_mx4300 is not set/CONFIG_TARGET_qualcommax_ipq807x_DEVICE_linksys_mx4300=y/g' .config
               && echo "CONFIG_PACKAGE_block-mount=y" >> .config
               && echo "CONFIG_PACKAGE_kmod-usb-storage-uas=y" >> .config
               && echo "CONFIG_PACKAGE_openssh-sftp-server=y" >> .config
               && echo "CONFIG_PACKAGE_luci-app-dockerman=y" >> .config
               && echo "CONFIG_PACKAGE_dockerd=y" >> .config
               && echo "CONFIG_PACKAGE_docker-compose=y" >> .config
               && echo "CONFIG_PACKAGE_docker=y" >> .config

            - name: Build Config
              run: make defconfig V=s -j$(nproc)

            - name: Build Images
              run: make V=s -j$(nproc)

            - name: Set current date as env variable
              run: echo "CUR_DATE=$(date +'%Y-%m-%d-T%H%M')" >> $GITHUB_ENV

            - name: Get SHORT SHA
              run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

            - name: Release
              uses: ncipollo/release-action@v1
              with:
                tag: mx4300-24_10_nss--${{ env.CUR_DATE }}--${{ env.SHORT_SHA }}
                artifacts: bin/targets/qualcommax/ipq807x/openwrt-qualcommax-ipq807x*.bin,bin/targets/qualcommax/ipq807x/openwrt-qualcommax-ipq807x-linksys_mx4300.manifest,.config
