name: test NSS Build

on: workflow_dispatch

jobs:
    build:
        name: test NSS Build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        
        steps:
            - name: Set up build dependencies
              run: |
                sudo apt update
                sudo apt install -y build-essential clang flex bison g++ gawk \
                    gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
                    python3-setuptools rsync swig unzip zlib1g-dev file wget

            - name: Checkout
              uses: actions/checkout@v4
              with:
                 ref: main
                 fetch-depth: 0

            - name: Set Git identity
              run: |
                    git config user.name "github-actions"
                    git config user.email "github-actions@github.com"
                    
            - name: Sync with immediate upstream fork (main branch)
              run: |
                    git remote add upstream https://github.com/qosmio/openwrt-ipq.git
                    git fetch upstream

                    # Checkout your branch
                    git checkout main

                    # Rebase onto upstream's branch of the same name
                    git rebase upstream/main || true

                    # Push the rebased branch back to your fork
                    git push origin main --force-with-lease

            - name: Clone config
              run: git clone https://${{ secrets.PAT }}@github.com/fhirrepo/custom_openwrt.git files/etc/uci-defaults && rm -rf files/etc/uci-defaults/.git && rm -rf files/etc/uci-defaults/*.yml
